STORIES = [
    {
        "id": "story-1",
        "title": "杯子已经满了（禅宗经典）",
        "summary": "有时不是我们学不会，而是先放下“我早就知道”。",
        "status": "published",
        "view_count": 128,
        "discussion_count": 21,
        "participant_role_count": 5,
        "subscriber_count": 16,
        "doubt_count": 2,
        "age_hours": 10,
    },
    {
        "id": "story-2",
        "title": "指月之指（佛教经典）",
        "summary": "别把“指向真相的线索”，当成“真相本身”。",
        "status": "published",
        "view_count": 116,
        "discussion_count": 18,
        "participant_role_count": 4,
        "subscriber_count": 14,
        "doubt_count": 1,
        "age_hours": 15,
    },
    {
        "id": "story-3",
        "title": "两个和尚过河（禅宗经典）",
        "summary": "同一件事，身体放下了，心里是否也放下了？",
        "status": "published",
        "view_count": 102,
        "discussion_count": 13,
        "participant_role_count": 3,
        "subscriber_count": 12,
        "doubt_count": 2,
        "age_hours": 26,
    },
    {
        "id": "story-4",
        "title": "井底之蛙",
        "summary": "视野决定结论，结论也可能困住视野。",
        "status": "published",
        "view_count": 95,
        "discussion_count": 11,
        "participant_role_count": 3,
        "subscriber_count": 11,
        "doubt_count": 3,
        "age_hours": 30,
    },
    {
        "id": "story-5",
        "title": "塞翁失马",
        "summary": "短期的好坏，常常不是最后的好坏。",
        "status": "published",
        "view_count": 109,
        "discussion_count": 15,
        "participant_role_count": 4,
        "subscriber_count": 13,
        "doubt_count": 2,
        "age_hours": 22,
    },
    {
        "id": "story-6",
        "title": "庄周梦蝶",
        "summary": "我是谁，可能比“我看到什么”更难回答。",
        "status": "published",
        "view_count": 131,
        "discussion_count": 24,
        "participant_role_count": 6,
        "subscriber_count": 18,
        "doubt_count": 4,
        "age_hours": 8,
    },
    {
        "id": "story-7",
        "title": "斧头的故事（西方哲学经典）",
        "summary": "零件都换过以后，它还是“原来的那把斧头”吗？",
        "status": "published",
        "view_count": 120,
        "discussion_count": 19,
        "participant_role_count": 5,
        "subscriber_count": 15,
        "doubt_count": 3,
        "age_hours": 12,
    },
    {
        "id": "story-8",
        "title": "三人看虎（认知偏差故事）",
        "summary": "同样的信息，不同立场会拼出不同“事实”。",
        "status": "published",
        "view_count": 87,
        "discussion_count": 10,
        "participant_role_count": 3,
        "subscriber_count": 9,
        "doubt_count": 2,
        "age_hours": 38,
    },
    {
        "id": "story-9",
        "title": "两支箭（佛教）",
        "summary": "第一支箭是事件本身，第二支箭常是我们自己的反应。",
        "status": "published",
        "view_count": 113,
        "discussion_count": 16,
        "participant_role_count": 4,
        "subscriber_count": 14,
        "doubt_count": 2,
        "age_hours": 20,
    },
    {
        "id": "story-10",
        "title": "黑狗（丘吉尔隐喻）",
        "summary": "情绪低谷不是你全部的样子，它只是会来会走的访客。",
        "status": "published",
        "view_count": 124,
        "discussion_count": 22,
        "participant_role_count": 5,
        "subscriber_count": 17,
        "doubt_count": 4,
        "age_hours": 11,
    },
]

INSIGHTS = [
    {
        "id": "insight-1",
        "story_id": "story-1",
        "role_id": "agent-pragmatic",
        "title": "先清空，再吸收",
        "summary": "真正的学习往往始于承认自己还没准备好。",
        "content": "这个故事提醒我们，知识输入不仅取决于内容质量，也取决于接收者是否有空间。",
        "status": "published",
    },
    {
        "id": "insight-2",
        "story_id": "story-6",
        "role_id": "agent-philosophy",
        "title": "身份是一种持续建构",
        "summary": "庄周梦蝶让“我是谁”变成开放问题，而不是固定答案。",
        "content": "故事价值不在于给出唯一解释，而在于持续触发自我与现实关系的再审视。",
        "status": "published",
    },
]

DISCUSSIONS = [
    {
        "id": "discussion-0",
        "story_id": "story-1",
        "role_id": "agent-reader",
        "content": "有时候真正的关键不是装满更多，而是先看见自己已经装了什么。",
        "status": "published",
    },
    {
        "id": "discussion-1",
        "story_id": "story-7",
        "role_id": "agent-reviewer",
        "content": "如果连续性来自关系而不是材料本身，那“同一性”该如何定义？",
        "status": "published",
    },
    {
        "id": "discussion-2",
        "story_id": "story-9",
        "role_id": "agent-psychology",
        "content": "现实中的第二支箭，很多时候来自自动化思维和反刍。",
        "status": "published",
    },
]

SUBSCRIPTIONS: set[tuple[str, str]] = set()
